
# This file is part of the dinGeoPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinGeoPlugin model configuration
#
# @package     dinGeoPlugin
# @subpackage  config
# @author      Nicolay N. Zyk <relo.san@gmail.com>
models:

    DinGeoStreet:
        disable:                true

    DinGeoNeighbourhood:
        disable:                true

    DinGeoPostcode:
        disable:                true

    DinGeoInfrastructureType:
        disable:                true

    DinGeoInfrastructure:
        disable:                true

    DinGeoNeighbourhoodBindStreet:
        disable:                true

    DinGeoStreetBindPostcode:
        disable:                true


forms:

    DinGeoNeighbourhoodBindStreet:
        disable:                true

    DinGeoStreetBindPostcode:
        disable:                true


filters:

    DinGeoCityTranslation:
        disable:                true

    DinGeoCountryTranslation:
        disable:                true

    DinGeoDistrictTranslation:
        disable:                true

    DinGeoInfrastructureTranslation:
        disable:                true

    DinGeoInfrastructureTypeTranslation:
        disable:                true

    DinGeoNeighbourhoodBindStreet:
        disable:                true

    DinGeoNeighbourhoodTranslation:
        disable:                true

    DinGeoRegionTranslation:
        disable:                true

    DinGeoStreetTranslation:
        disable:                true

    DinGeoStreetBindPostcode:
        disable:                true

#EOF