
# This file is part of the dinGeoPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinGeoPlugin model configuration
#
# @package     dinGeoPlugin
# @subpackage  config
# @author      Nicolay N. Zyk <relo.san@gmail.com>

din_geo_city_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinGeoCity'
        module:                 'dinGeoCityAdmin'
        prefix_path:            '/adm/geo/country/:country_id/region/:region_id/district/:district_id/city'
        column:                 'id'
        with_wildcard_routes:   true

din_geo_district_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinGeoDistrict'
        module:                 'dinGeoDistrictAdmin'
        prefix_path:            '/adm/geo/country/:country_id/region/:region_id/district'
        column:                 'id'
        with_wildcard_routes:   true

din_geo_region_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinGeoRegion'
        module:                 'dinGeoRegionAdmin'
        prefix_path:            '/adm/geo/country/:country_id/region'
        column:                 'id'
        with_wildcard_routes:   true

din_geo_country_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinGeoCountry'
        module:                 'dinGeoCountryAdmin'
        prefix_path:            '/adm/geo/country'
        column:                 'id'
        with_wildcard_routes:   true

#EOF